---
title: "RWorksheet#5_group(Lomibao,rabago and andigan)"
output: pdf_document
date: "2024-11-18"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(kableExtra)
library("rvest")
library("polite")
library("dplyr")


polite::use_manners(save_as = 'polite_scrape.R')
  
url <- "https://www.imdb.com/chart/toptv/"
webpage <- read_html(url)  
 session <- bow(url, 
                 user_agent = "Student education purpose")
 session
 page <- scrape(session)  
```
scraping the title 
```{r}
 title <- page%>%html_nodes('h3.ipc-title__text')%>%html_text()
 title <- title[2:26]
 title
```

```{r}
title_list <- as.data.frame(title[1:50])
colnames(title_list)<-"ranks"

```
spliting the data frame
```{r}
split_df <- strsplit(as.character(title_list$ranks),".",fixed = TRUE)
split_df<- data.frame(do.call(rbind,split_df))
split_df
```
renaming the columns
```{r}

split_df<-split_df[-c(3,4)]
colnames(split_df)<- c("Ranks","Titles")
split_df
```
scraping the star- rating 
```{r}
ratings<- page %>% 
  html_nodes('span.ipc-rating-star--rating') %>%
  html_text()
ratings
```
scraping the numbers of vote 
```{r}
number_votes <- page %>%
  html_nodes("span.ipc-rating-star--voteCount") %>%
  html_text()
number_votes
```
scraping the number of episode 
```{r}
num_ep <- page %>%
  html_nodes("span.ipc-title__subtext")%>%
  html_text()
num_ep <- as.data.frame(num_ep[1:25])
colnames(num_ep) <- "episode"

```
scraping the year release
```{r}
year <- scrape(session) %>%
  html_nodes("span.sc-300a8231-7 eaXxft cli-title-metadata-item") %>%
  html_text()
year
year <- as.data.frame(year[1:25])
colnames(year)<- "year"
```
creating csv file for every one of the data. 
```{r}
#title and ranks 
rank_title <- data.frame(
  rank_title = split_df)
write.csv(rank_title,file = "title.csv")
#ranting 
write.csv(rating,file = "star_rating.csv")
#vote count 
write.csv(number_votes,file = "vote_count.csv")
#year
 # write.csv(year = "released_year.csv")
#number of episode 
# write.csv(num_ep = "number_episode.csv")

```
checking the length. 
```{r}
cat("Show Titles length: ", length(title), "\n")
cat("Show Ratings length: ", length(ratings), "\n")
cat("Number of Votes length: ", length(number_votes), "\n")
cat("Episode Counts length: ", length(episodes), "\n")
cat("Release Years length: ", length(release_years), "\n")
```

```{r}

```
Combining them all to a data frame. 
```{r}
  imdb_top_tv_shows <- data.frame(
  Title = rank_title,
  Rating = ratings,
  Votes = number_votes,
 # Episode = episodes,
 # Release_Year = release_years,
  stringsAsFactors = FALSE
  )
imdb_top_tv_shows

```

